version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    env_file:
      - ./backend/.env
    volumes:
      # Persistent data volume for ChromaDB
      - chroma_db:/app/chroma_db
    command: uvicorn app.main:app --host 0.0.0.0 --port 7000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "6173:6173"
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=production
    command: npm run dev -- --host --port 6173
    depends_on:
      - backend

volumes:
  chroma_db:
    driver: local
