version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - chroma_db:/app/chroma_db
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 7000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "6173:6173"
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:7000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: >
      sh -c "npm install && npm run dev -- --host --port 6173"
    depends_on:
      - backend

volumes:
  chroma_db:
